# Markdownlint設定ファイル
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# デフォルトですべてのルールを有効にする
default: true

# 行の長さ制限を無効にする（日本語対応）
MD013: false

# リスト項目のインデント（2スペース）
MD007:
  indent: 2

# コードブロックのスタイル（fenced）
MD046:
  style: fenced

# 見出しの周りの空行
MD022:
  lines_above: 1
  lines_below: 1

# リストの周りの空行
MD032: true

# インライン HTML を許可
MD033: false

# 重複する見出しを許可（同じレベルの場合）
MD024:
  allow_different_nesting: true

# 外部リンクの検証をスキップ
MD034: false

# 強調のスタイル（アスタリスク）
MD049:
  style: asterisk

MD050:
  style: asterisk
